"""revision tbls

Revision ID: 322f37e73c0f
Revises: a0e3e54f8cf2
Create Date: 2026-02-04 19:04:51.469805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "322f37e73c0f"
down_revision: Union[str, None] = "a0e3e54f8cf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_items", sa.Column("count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "count")
    # ### end Alembic commands ###
