"""revision tbls

Revision ID: a0e3e54f8cf2
Revises: a23e9196f12e
Create Date: 2026-02-04 18:03:08.779829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a0e3e54f8cf2"
down_revision: Union[str, None] = "a23e9196f12e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "parent_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories", "parent_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###
